### ISSUE TITLE
Create example/main.rs file and minor cleanup

### ISSUE THREAD

**Issue by slaterb1** [slaterb1/rettle#16]
# Overview
Currently all test examples are built and run from `bin/main.rs`. Project on release will not have this file. The code here needs to be moved to `examples/main.rs`. In addition some minor cleanup needs to happen to wrap up this project.

# Tasks
- [x] move `bin/main.rs` to `examples/main.rs`
- [x] add documentation to all modules in project
- [x] update documentation to include links to other crates (place holder for now until everything is opensource + CI)
- [x] add LICENSE
- [x] add Contributing.md
- [x] check on changing `Fn` based traits to `fn` function references
