### ISSUE TITLE
Update docs to explain that Tea needs to be overwritten when inherited

### ISSUE THREAD

**Issue by slaterb1** [slaterb1/rettle#2]
# Overview
Tea structure needs to be simplified and only include the fields necessary. Need to consider creating Tea as a Trait which can be pulled into other libraries that manipulate data (or keep it a struct but give it a trait definition).

Successfully created Tea as trait, but need to investigate the following:
- [x] lifetimes of Box objects (Tea is now a Box holding teas with `Trait: Tea`)
- [x] adding `new()` to Tea Trait, error is that it cannot return `Box<dyn Tea>`

# Tasks
- [x] decide if Trait of struct is better for Tea
- [x] simplify base "Tea" struct in library
- [x] investigate the above
- [x] update README
- [x] update Tea documentation

# R&D
**Box lifetimes:** Did some research on Box lifetimes. Lifetimes of values `5`, `"some string"`, `heap memory` has `'static` lifetimes that are defined to exist the entire length of the problem. BUT has the variables that contain these `values` go out of scope, the memory is reclaimed via the `Drop` trait. Therefore, memory concerns that I had surrounding `'static` are not actually a problem.
