### ISSUE TITLE
Update Steep exec function to work with optional passed parameters

### ISSUE THREAD

**Issue by slaterb1** [slaterb1/rettle#3]
# Overview
Current Steep only accepts `&Tea` and a parameter. Need to investigate best way to pass any arguments (i.e. additional instructions, file paths field to target for update).

# Research
- [x] generic function structure / wrapper

# Results
There are a few mechanisms that could work:
- creating a wrapper that has `Option<>` values for the params, but specifies all params in wrapper https://stackoverflow.com/questions/28951503/how-can-i-create-a-function-with-a-variable-number-of-arguments
- create a new `Argument` trait that can be implemented on any struct of "arguments" to be passed to function (`Box<dyn Argument>`)

*Leaning towards `Argument` trait method, and make the `exec` functions accept args as `Option<>`

# Tasks
- [x] research generic function structure
- [ ] create Argument trait (could be empty, aside from `as_any`?)
- [ ] update `exec` function to selectively pass arguments
